export const enum QueryKeys {
  Branches = 'branches',
  ReportLead = 'report-lead',
  ChecklistTeacher = 'check-list_teacher',
  ChecklistCourse = 'check-list_course',
  ReportsLeadsSellers = 'leads-sellers',
  ReportLeadsList = 'leads-list',
  ReportLeadsChart = 'leads-card-chart',
  FinancialsIncomeOverview = 'financials_income_overview',
  LeadsDescriptionUpdate = 'leads-description-update',
  LeadDetail = 'lead-detail',
  TeacherDetail = 'teacher-detail',
  Groups = 'groups',
  EmployeeSellers = 'sellers',
  EmployeeSellersRealTime = 'sellers-real-time',
}
