import { GridLocaleText } from "@mui/x-data-grid";

// @ts-ignore
export const uzbekLocaleText: GridLocaleText = {
    noRowsLabel: 'Hech qanday ma\'lumot yo\'q',
    noResultsOverlayLabel: 'Natijalar topilmadi',
    errorOverlayDefaultLabel: 'Xatolik yuz berdi.',
    columnsPanelTextFieldLabel: 'Ustun topish',
    toolbarDensity: 'Zichlik',
    toolbarDensityLabel: 'Zichlik',
    toolbarDensityCompact: 'Kompakt',
    toolbarDensityStandard: 'Standart',
    toolbarDensityComfortable: 'Qulay',
    toolbarColumns: 'Ustunlar',
    toolbarColumnsLabel: 'Ustunlarni tanlash',
    toolbarFilters: 'Filtrlar',
    toolbarFiltersLabel: 'Filtrlarni ko\'rsatish',
    toolbarExport: 'Eksport',
    toolbarExportLabel: 'Eksport',
    toolbarExportCSV: 'CSV sifatida yuklab olish',
    toolbarExportPrint: 'Chop etish',
    toolbarExportExcel: 'Excel sifatida yuklab olish',
    columnsPanelTextFieldPlaceholder: 'Ustun sarlavhasi',
    columnsPanelDragIconLabel: 'Ustun tartibini o\'zgartirish',
    columnsPanelShowAllButton: 'Hammasini ko\'rsatish',
    columnsPanelHideAllButton: 'Hammasini yashirish',
    filterPanelAddFilter: 'Filter qo\'shish',
    filterPanelDeleteIconLabel: 'O\'chirish',
    filterPanelLinkOperator: 'Mantiqiy operator',
    filterPanelOperators: 'Operatorlar',
    filterPanelOperatorAnd: 'Va',
    filterPanelOperatorOr: 'Yoki',
    filterPanelColumns: 'Ustunlar',
    filterPanelInputLabel: 'Qiymat',
    filterPanelInputPlaceholder: 'Qiymat',
    filterOperatorContains: 'O\'z ichiga oladi',
    filterOperatorEquals: 'Teng',
    filterOperatorStartsWith: 'Bilan boshlanadi',
    filterOperatorEndsWith: 'Bilan tugaydi',
    filterOperatorIs: 'Bu',
    filterOperatorNot: 'Emas',
    filterOperatorAfter: 'Keyin',
    filterOperatorOnOrAfter: 'Yoki keyin',
    filterOperatorBefore: 'Oldin',
    filterOperatorOnOrBefore: 'Yoki oldin',
    filterOperatorIsEmpty: 'Bo\'sh',
    filterOperatorIsNotEmpty: 'Bo\'sh emas',
    columnMenuLabel: 'Menyu',
    columnMenuShowColumns: 'Ustunlarni ko\'rsatish',
    columnMenuFilter: 'Filtrlash',
    columnMenuHideColumn: 'Yashirish',
    columnMenuUnsort: 'Saralashni bekor qilish',
    columnMenuSortAsc: 'O\'sish tartibida saralash',
    columnMenuSortDesc: 'Kamayish tartibida saralash',
    columnHeaderFiltersTooltipActive: (count: number) => `${count} ta faol filter`,
    columnHeaderFiltersLabel: 'Filtrlarni ko\'rsatish',
    columnHeaderSortIconLabel: 'Saralash',
    footerRowSelected: (count: number) =>
      count !== 1
        ? `${count.toLocaleString()} qator tanlandi`
        : `${count.toLocaleString()} qator tanlandi`,
    footerTotalRows: 'Jami qatorlar:',
    // Boolean cell text
    booleanCellTrueLabel: 'Ha',
    booleanCellFalseLabel: 'Yo\'q',
    // Actions cell more text
    actionsCellMore: 'Ko\'proq',
};